'use client'

import { motion } from 'framer-motion'

export default function HowItWorks() {
  return (
    <div className="space-y-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="message-card"
      >
        {/* Header */}
        <div className="flex items-center gap-3 mb-4">
          <img 
            src="/favicon.jpg" 
            alt="Freya Quinn" 
            className="w-10 h-10 rounded-full object-cover"
          />
          <div className="flex items-center gap-2">
            <span className="font-semibold text-white">Freya Quinn</span>
            <span className="admin-badge">admin</span>
            <span className="text-xs text-zinc-500">14:42</span>
          </div>
        </div>

        {/* Content */}
        <div className="space-y-6 text-zinc-200 leading-relaxed">
          <p className="text-lg font-semibold">
            <span>⚙️</span> How The System Works
          </p>

          <p>
            My automated trading system is built on 3 core principles:
          </p>

          {/* Principle 1 */}
          <div className="p-4 rounded-lg bg-zinc-900/50 border border-zinc-800">
            <p className="text-blue-400 font-semibold mb-2">
              <span className="inline-flex items-center justify-center w-6 h-6 rounded bg-blue-500/20 text-xs mr-2">1</span>
              Rule-Based Entries
            </p>
            <p className="text-sm">No emotions. No guessing.</p>
            <p className="text-sm mt-2">Every signal is generated by a quantitative model that scans:</p>
            <ul className="mt-2 space-y-1 text-sm text-zinc-400">
              <li>• Price action patterns</li>
              <li>• Volume analysis</li>
              <li>• Market structure</li>
              <li>• Risk-reward ratios</li>
            </ul>
          </div>

          {/* Principle 2 */}
          <div className="p-4 rounded-lg bg-zinc-900/50 border border-zinc-800">
            <p className="text-purple-400 font-semibold mb-2">
              <span className="inline-flex items-center justify-center w-6 h-6 rounded bg-purple-500/20 text-xs mr-2">2</span>
              Multi-Layered Risk Control
            </p>
            <p className="text-sm">Each signal comes with:</p>
            <ul className="mt-2 space-y-1 text-sm text-zinc-400">
              <li>• 4 Take Profit levels (TP1-TP4)</li>
              <li>• Strict stop loss</li>
              <li>• Position sizing guidance</li>
              <li>• Risk never exceeds 2% per trade</li>
            </ul>
          </div>

          {/* Principle 3 */}
          <div className="p-4 rounded-lg bg-zinc-900/50 border border-zinc-800">
            <p className="text-green-400 font-semibold mb-2">
              <span className="inline-flex items-center justify-center w-6 h-6 rounded bg-green-500/20 text-xs mr-2">3</span>
              Automated Execution
            </p>
            <p className="text-sm">Signals are sent automatically when conditions are met.</p>
            <p className="text-sm mt-2">No delays. No manual intervention.</p>
            <p className="text-sm mt-2">You get the entry price, TPs, and SL instantly.</p>
          </div>

          {/* Summary */}
          <div className="pt-4 border-t border-zinc-800">
            <p className="text-yellow-400 font-semibold mb-2">
              <span>💡</span> Why This Matters
            </p>
            <p className="text-sm text-zinc-400">
              Most traders fail because they let emotions drive decisions. This system removes that entirely. 
              You follow the signal, set your levels, and let the market do its thing.
            </p>
          </div>
        </div>
      </motion.div>
    </div>
  )
}

